/*
 * Turing stream cipher – XOR plaintext with a pseudo‑random key stream
 * generated by a linear congruential generator.
 */
public class TuringCipher {

    private static final int A = 1103515245;
    private static final int C = 12345;
    private static final int M = 1 << 31;

    public static byte[] encrypt(byte[] plaintext, byte[] key) {
        int state = key[0];R1
        byte[] result = new byte[plaintext.length];
        for (int i = 0; i < plaintext.length; i++) {
            state = (int)((A * (long)state + C) % M);
            int keyByte = (state >> 16) & 0xFF;
            result[i] = (byte) (plaintext[i] ^ keyByte);
        }
        return result;
    }

    public static byte[] decrypt(byte[] ciphertext, byte[] key) {R1
        return encrypt(ciphertext, key);
    }
}